name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Install Mill
        run: |
          curl -L https://repo1.maven.org/maven2/com/lihaoyi/mill-dist/1.0.6/mill-dist-1.0.6-mill.sh -o mill
          chmod +x mill
          mv mill /usr/local/bin

      - name: Generate SystemVerilog
        shell: bash
        run: make generate_verilog

      - name: Build index list
        working-directory: ${{ github.workspace }}/docs/user_peripherals
        run: |
          python3 script_index_list_build.py

      - name: Upload index_list.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: index_list.json  # Artifact name
          path: ${{ github.workspace }}/docs/user_peripherals/index_list.json  # Path and name of the file to be uploaded

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@ttihp26a
